---
title: "ElPaso_bus"
author: "Charlie Huemmler"
date: "2023-01-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# El Paso Bus Network Analysis

```{r}
library(sf)
library(tidyverse)
library(tidycensus)
library(tigris)
library(boxr)
library(lubridate)
library(here)

census_api_key("746ea8916547306ae2abf2aafe059e1a1b70b98a", overwrite = TRUE)
#box_auth(client_id = "your_client_id", client_secret = "your_client_secret")


```

```{r}
censusvars <- c("B01001_001E", # ACS total Pop estimate
              "B25002_001E", # Estimate of total housing units
              "B25002_003E", # Number of vacant housing units
              "B19013_001E", # Median HH Income ($)
              "B02001_002E", # People describing themselves as "white alone"
              "B06009_006E") #


elpaso <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = censusvars, 
                             geometry = T,
                             state = "TX", 
                             county = "El Paso", 
                             output = "wide") 

```


```{r}
ggplot()+
  geom_sf(data = elpaso)
```

```{r}
routes <- read_sf('C:/Users/cchue/Documents/Penn MUSA/Spring/Practicum/Data/BusRoutes.shp')

```

```{r}
ggplot()+
  geom_sf(data = elpaso)+
  geom_sf(data = routes, color = 'red')
```


