---
title: "ExploratoryAnalysis"
author: "Yingxue Ou"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data

## ACS Census

```{r}
library(sf)
library(tidyverse)
library(tidycensus)
library(tigris)
library(lubridate)

census_api_key("746ea8916547306ae2abf2aafe059e1a1b70b98a", overwrite = TRUE)

```

```{r}
censusvars <- c("B01001_001E", # ACS total Pop estimate
              "B25002_001E", # Estimate of total housing units
              "B25002_003E", # Number of vacant housing units
              "B19013_001E", # Median HH Income ($)
              "B02001_002E", # People describing themselves as "white alone"
              "B06009_006E",
              "B01001I_001E", # Hispanic or Latino 
              "B08014_001E",
              "B09001_002E", # Population under 18
              "B10052_002E", # Disability
              "B25075_001E", # House value
              "B08014_002E") # No vehicle available


elpaso <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = censusvars, 
                             geometry = T,
                             state = "TX", 
                             county = "El Paso", 
                             output = "wide") 

```

```{r rename column}
elpaso <- elpaso %>%
  rename(
    total_pop.2020 = B01001_001E,
    total_HU.2020 = B25002_001E,
    total_vacant.2020 = B25002_003E,
    med_HH_Income.2020 = B19013_001E,
    total_White.2020 = B02001_002E,
    total_GradDeg.2020 = B06009_006E,
    total_HL.2020 = B01001I_001E,
    noV.2020 = B08014_002E,
    under18.2020 = B09001_002E,
    disAb.2020 = B10052_002E,
    Value = B25075_001E
  ) %>%
    mutate(vacancyPct.2020 = total_vacant.2020/total_HU.2020,
         pctWhite.2020 = total_White.2020/total_pop.2020,
         pctHL.2020 = total_HL.2020/total_pop.2020,
         pctNV.2020 = noV.2020/total_HU.2020*100,
         pctUnder18.2020 = under18.2020/total_pop.2020,
         pctDisAb.2020 = disAb.2020/total_pop.2020,
         ) %>%
  st_as_sf(crs = 4326) # Turn shp into sf object and project as WGS84

```

## Open Street Map Data

```{r}
ParkandRecreation <- 
  st_read("./OpenStreetMap/ParkandRecreationFacilities/ParkandRecreationFacilities.shp") %>%
  st_transform('ESRI:102286')

Schools <-
  st_read("./OpenStreetMap/Schools/Schools.shp") %>%
  st_transform('ESRI:102286')

Centerline <- 
  st_read("./OpenStreetMap/EPCenterline/EPCenterline.shp") %>%
  st_transform('ESRI:102286')

BikeLanes <-
  st_read("./OpenStreetMap/BikeLanes/BikeLanesFinal.shp") %>%
  st_transform('ESRI:102286')

TIRZ <-
  st_read("./OpenStreetMap/TIRZ/TIRZ.shp") %>%
  st_transform('ESRI:102286')

PID <-
  st_read("./OpenStreetMap/PublicImprovementDistrict/PID.shp") %>%
  st_transform('ESRI:102286')


```

# Exploratory analysis

## Exploring distributions

### Population

```{r plot_noV, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = total_pop.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Total population",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### Income distribution

```{r IncomeDistribution warning = FALSE, cache = TRUE}
ggplot(elpaso)+
  geom_histogram(aes(med_HH_Income.2020))

```



### No vehicle distribution

```{r NovehicleDistribution warning = FALSE, cache = TRUE}
ggplot(elpaso)+
  geom_histogram(aes(pctNV.2020))

```

```{r plot_noV, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctNV.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those claim no vehicle households by tract (%)",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### Race

```{r plot_whitealone, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctWhite.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those identifying as 'white only' by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

```{r plot_HL, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctHL.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those identifying as 'Hispanic or Latino' by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### Age

```{r plot_under18, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctUnder18.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those under 18 years old by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```
### Ability/disability

```{r plot_disability, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctDisAb.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those claim disability by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### House value

```{r plot_HouseValue, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = Value),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "House value by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

## Replica Data

```{r load_replica}
library(geojsonio)
destination <- geojson_read("../data/trip_destinations.geojson",  what = "sp")
origin <- geojson_read("../data/trip_origins.geojson",  what = "sp")
```


```{r load_replica sf and here}
destination <- read_sf(paste(data_folder, "/trip_destinations.geojson", sep = ''))

origin <- read_sf(paste(data_folder, "/trip_origins.geojson", sep = ''))
```

```{r}
ggplot(origin)+
  geom_sf()
```



```{r}

# 'fortify' the data to get a dataframe format required by ggplot2
library(broom)
destination_df <- as.data.frame(destination)
destination_filtered <- subset(destination_df, FIPS_tract %in% elpaso$GEOID)

origin_df <- as.data.frame(origin)
origin_filtered <- subset(origin_df, FIPS_tract %in% elpaso$GEOID)

destination_fortified <- tidy(destination)
origin_fortified <- tidy(origin)
```

```{r basemap_setting}
#creating north arrow and scale bar, motivation from GISTools package
arrow_data <- function(xb, yb, len) {
  s <- len
  arrow.x = c(0,0.5,1,0.5,0) - 0.5
  arrow.y = c(0,1.7  ,0,0.5,0)
  adata <- data.frame(aX = xb + arrow.x * s, aY = yb + arrow.y * s)
  return(adata)
}

scale_data <- function(llx,lly,len,height){
  box1 <- data.frame(x = c(llx,llx+len,llx+len,llx,llx),
                     y = c(lly,lly,lly+height,lly+height,lly))
  box2 <- data.frame(x = c(llx-len,llx,llx,llx-len,llx-len),
                     y = c(lly,lly,lly+height,lly+height,lly))
  return(list(box1,box2))
}

x_cent <- 830000
len_bar <- 3000
offset_scaleNum <- 64300
arrow <- arrow_data(xb=x_cent,yb=67300,len=2500)
scale_bxs <- scale_data(llx=x_cent,lly=65000,len=len_bar,height=750)

lab_data <- data.frame(x=c(x_cent, x_cent-len_bar, x_cent, x_cent+len_bar, x_cent),
                       y=c( 72300, offset_scaleNum, offset_scaleNum, offset_scaleNum, 66500),
                       lab=c("N","0","3","6","Kilometers"))

```

```{r basemape_creating}
ggtract<-fortify(elpaso, region = "geometry") 

ggplot()+
  geom_sf(data = elpaso, fill="#69b3a2", color="white")+
  geom_polygon(data=arrow, fill='black', aes(x=aX, y=aY)) +
  geom_polygon(data=scale_bxs[[1]], fill='grey', color='black', aes(x=x, y = y)) + 
  geom_polygon(data=scale_bxs[[2]], fill='white', color='black', aes(x=x, y = y)) + 
  geom_text(data=lab_data, size=4, aes(x=x,y=y,label=lab)) +
  theme_void() +
  labs(
    title = "Origin layer",
    subtitle = "",
    caption = "Data: Replica city of El Paso")

basemap
```


```{r}
library(ggplot2)

ggplot() +
  geom_hex(data = destination_filtered, color='white', alpha=0.85, size=0.1, aes( x = centroidLon, y = centroidLat, fill = tripsByDestination), bins = 70) +
  scale_fill_continuous(type = "viridis") +
  scale_fill_brewer(name="Destination trips count", palette="OrRd")
  theme_bw()
```

```{r}

ggplot(data = origin_fortified, aes( x = long, y = lat, group = group) )+
  geom_hex(bins = 70) +
  scale_fill_continuous(type = "viridis") +
    labs(
    title = "Origin",
    subtitle = "",
    caption = "Data: Replica City of El Paso")+
  theme_bw()

ggplot(data = destination_fortified, aes( x = long, y = lat, group = group) )+
  geom_hex(bins = 70) +
  scale_fill_continuous(type = "viridis") +
    labs(
    title = "Destination",
    subtitle = "",
    caption = "Data: Replica City of El Paso")+
  theme_bw()



```


```{r}

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

ggplot()+
  geom_sf(data = elpaso %>%
          st_transform(crs=4326), color = "grey", fill = "transparent")+
  geom_point(data = origin_filtered, aes(x=centroidLon, y = centroidLat, color = tripsByOrigin), fill = "transparent", alpha = 0.4, size = 2)+
  labs(title="Trips by Origin in El Paso County")+
  mapTheme

ggplot()+
  geom_sf(data = elpaso %>%
          st_transform(crs=4326), color = "grey", fill = "transparent")+
  geom_point(data = destination_filtered, aes(x=centroidLon, y = centroidLat, color = tripsByDestination), fill = "transparent", alpha = 0.4, size = 2)+
  labs(title="Trips by Destinatin in El Paso County")+
  mapTheme


```


```{r}
elpaso$tripsByDestination  <- destination_filtered$tripsByDestination[match(elpaso$GEOID, destination_filtered$FIPS_tract)]
elpaso$tripsByDestination_sqmi <- destination_filtered$tripsByDestination_sqmi[match(elpaso$GEOID, destination_filtered$FIPS_tract)]
elpaso$tripsByOrigin <- origin_filtered$tripsByOrigin[match(elpaso$GEOID, origin_filtered$FIPS_tract)]
elpaso$tripsByOrigin_sqmi <- origin_filtered$tripsByOrigin_sqmi[match(elpaso$GEOID, origin_filtered$FIPS_tract)]

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByOrigin),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Origin",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByDestination),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Destination",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByOrigin_sqmi),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Origin",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByDestination_sqmi),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Destination",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
```

