---
title: "El Paso Bus Network"
output:
  html_document: 
    toc: true
    toc_float: true
    toc_collapsed: true
    code_folding: hide
    pdf_document: default
date: "2023-1-16"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
  warning=FALSE,
  message=FALSE,
  results='hide')

library(sf)
library(tidyverse)
library(tidycensus)
library(tigris)
library(boxr)
library(lubridate)
library(here)
library(readxl)

census_api_key("746ea8916547306ae2abf2aafe059e1a1b70b98a", overwrite = TRUE)
#box_auth(client_id = "your_client_id", client_secret = "your_client_secret")

```

## Load 2021 Ridership data

```{r}
data_folder <- file.path(here() %>% dirname(), 'data')


#stops
stops <- read.csv(paste(data_folder, "/stops.csv", sep = ''))

#totalboardings2021
jan <- read_excel(paste(data_folder, "/totalboardings2022.xlsx", sep = ""),
                                  sheet = "Jan-Aug")

sep <- read_excel(paste(data_folder, "/totalboardings2022.xlsx", sep = ""),
                                  sheet = "Sept - Dec")

ridership <- rbind(jan, sep)

```

```{r}
ridership$Date <- ridership$Date %>% 
  as.character() %>% 
  substring(2) %>% 
  as.Date(format = "%Y%m%d")
```

## Load stops data

```{r}
stops <- read.csv(paste(data_folder, "/stops.csv", sep = ''))
stops_sf <- stops %>% st_as_sf(coords = c('stop_lon','stop_lat'))
```

```{r find stops without ridership data}
uniq_riderstops <- ridership$TP %>% unique()

stops_sf$ridershipdata <- ifelse(stops_sf$stop_name %in% uniq_riderstops,'y','n')

ggplot(stops_sf)+
  geom_sf(aes(color = ridershipdata, size = ifelse(ridershipdata == 'n', 3,1)))

print(stops_sf %>% filter(ridershipdata == 'n') %>% pull(stop_name))
```

## el paso open data portal data

```{r}
road_centerlines <- read_sf(paste(data_folder, "/EPCenterline.shp", sep = ''))

bike_lanes <- read_sf(paste(data_folder, "/BikeLanesFinal.shp", sep = ''))

parks <- read_sf(paste(data_folder, "/ParkandRecreationFacilities.shp", sep = ''))

schools <- read_sf(paste(data_folder, "/Schools.shp", sep = ''))


futureLU <- read_sf(paste(data_folder, "/FutureLandUse.shp", sep = ''))


```

## load census data 

```{r}
censusvars <- c("B01001_001E", # ACS total Pop estimate
              "B25002_001E", # Estimate of total housing units
              "B25002_003E", # Number of vacant housing units
              "B19013_001E", # Median HH Income ($)
              "B02001_002E", # People describing themselves as "white alone"
              "B06009_006E",
              "B01001I_001E", # Hispanic or Latino 
              "B08014_001E",
              "B09001_002E", # Population under 18
              "B10052_002E", # Disability
              "B25075_001E", # House value
              "B08014_002E") # No vehicle available


elpaso <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = censusvars, 
                             geometry = T,
                             state = "TX", 
                             county = "El Paso", 
                             output = "wide") 

```




```{r rename column}
elpaso <- elpaso %>%
  rename(
    total_pop.2020 = B01001_001E,
    total_HU.2020 = B25002_001E,
    total_vacant.2020 = B25002_003E,
    med_HH_Income.2020 = B19013_001E,
    total_White.2020 = B02001_002E,
    total_GradDeg.2020 = B06009_006E,
    total_HL.2020 = B01001I_001E,
    noV.2020 = B08014_002E,
    under18.2020 = B09001_002E,
    disAb.2020 = B10052_002E,
    Value = B25075_001E
  ) %>%
    mutate(vacancyPct.2020 = total_vacant.2020/total_HU.2020,
         pctWhite.2020 = total_White.2020/total_pop.2020,
         pctHL.2020 = total_HL.2020/total_pop.2020,
         pctNV.2020 = noV.2020/total_HU.2020*100,
         pctUnder18.2020 = under18.2020/total_pop.2020,
         pctDisAb.2020 = disAb.2020/total_pop.2020,
         ) %>%
  st_as_sf(crs = 4326) # Turn shp into sf object and project as WGS84

```




## Exploring distributions

### Population

```{r plot_noV1, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = total_pop.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Total population",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### Income distribution

```{r IncomeDistribution, warning = FALSE, cache = TRUE}
ggplot(elpaso)+
  geom_histogram(aes(med_HH_Income.2020))

```



### No vehicle distribution

```{r NovehicleDistribution, warning = FALSE, cache = TRUE}
ggplot(elpaso)+
  geom_histogram(aes(pctNV.2020))

```

```{r plot_noV, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctNV.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those claim no vehicle households by tract (%)",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### Race

```{r plot_whitealone, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctWhite.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those identifying as 'white only' by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

```{r plot_HL, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctHL.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those identifying as 'Hispanic or Latino' by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### Age

```{r plot_under18, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctUnder18.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those under 18 years old by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```
### Ability/disability

```{r plot_disability, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = pctDisAb.2020),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of those claim disability by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```

### House value

```{r plot_HouseValue, warning = FALSE, cache = TRUE}
ggplot()+
  geom_sf(data = elpaso, aes(fill = Value),
          color = "transparent")+
  geom_sf(data = elpaso %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "House value by tract",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
  
```
## replica data

```{r}
destination <- read_sf(paste(data_folder, "/trip_destinations.geojson", sep = ''))

origin <- read_sf(paste(data_folder, "/trip_origins.geojson", sep = ''))
```

```{r fortify}
# 'fortify' the data to get a dataframe format required by ggplot2
library(broom)
destination_df <- as.data.frame(destination)
destination_filtered <- subset(destination_df, FIPS_tract %in% elpaso$GEOID)

origin_df <- as.data.frame(origin)
origin_filtered <- subset(origin_df, FIPS_tract %in% elpaso$GEOID)

```

```{r}
elpaso_outline <- elpaso %>% st_union() %>% sf::st_cast()

hex <- st_make_grid(elpaso_outline, cellsize = .01, crs = 4269,  square = F)  %>%  st_sf() %>%
  mutate(uniqueID = rownames(.))

hex <- hex[elpaso,]

basemap <- ggplot(hex)+
  geom_sf()
```

```{r}
library(ggplot2)

basemap +
  geom_hex(data = destination_filtered, color='white', alpha=0.85, size=0.1, aes( x = centroidLon, y = centroidLat, fill = tripsByDestination), bins = 70) +
  scale_fill_continuous(type = "viridis") +
  scale_fill_brewer(name="Destination trips count", palette="OrRd")
  theme_bw()
```


```{r}

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

ggplot()+
  geom_sf(data = elpaso %>%
          st_transform(crs=4326), color = "grey", fill = "transparent")+
  geom_point(data = origin_filtered, aes(x=centroidLon, y = centroidLat, color = tripsByOrigin), fill = "transparent", alpha = 0.4, size = 2)+
  labs(title="Trips by Origin in El Paso County")+
  mapTheme

ggplot()+
  geom_sf(data = elpaso %>%
          st_transform(crs=4326), color = "grey", fill = "transparent")+
  geom_point(data = destination_filtered, aes(x=centroidLon, y = centroidLat, color = tripsByDestination), fill = "transparent", alpha = 0.4, size = 2)+
  labs(title="Trips by Destinatin in El Paso County")+
  mapTheme


```


```{r}
elpaso$tripsByDestination  <- destination_filtered$tripsByDestination[match(elpaso$GEOID, destination_filtered$FIPS_tract)]
elpaso$tripsByDestination_sqmi <- destination_filtered$tripsByDestination_sqmi[match(elpaso$GEOID, destination_filtered$FIPS_tract)]
elpaso$tripsByOrigin <- origin_filtered$tripsByOrigin[match(elpaso$GEOID, origin_filtered$FIPS_tract)]
elpaso$tripsByOrigin_sqmi <- origin_filtered$tripsByOrigin_sqmi[match(elpaso$GEOID, origin_filtered$FIPS_tract)]

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByOrigin),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Origin",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByDestination),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Destination",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByOrigin_sqmi),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Origin",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")

ggplot()+
  geom_sf(data = elpaso, aes(fill = tripsByDestination_sqmi),
          color = "transparent")+
  geom_sf(data = elpaso %>%
          st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Trips by Destination",
    subtitle = "",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
```

# outline of system
## BRIO Lines
## Local Busses - What we get to effect!

## Model of where ridership exists 



