---
title: "pres1 graphics"
author: "Charlie Huemmler"
date: "2023-02-18"
output:
  html_document: 
    toc: true
    toc_float: true
    toc_collapsed: true
    code_folding: hide
    pdf_document: default
date: "2023-1-16"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
  warning=FALSE,
  message=FALSE,
  results='hide')
```

```{r}
library(sf)
library(tidyverse)
library(tidycensus)
library(tigris)
library(lubridate)
library(here)
library(readxl)
library(viridis)
library(stplanr)
library(paletteer)
library(scales)
library(gganimate)
library(transformr)

sf::sf_use_s2(FALSE)
options(scipen = 999)



source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

```

```{r}
data_folder <- file.path(here() %>% dirname(), 'data')
transitroutes <-  read_sf(paste(data_folder, "/transit_lines.geojson", sep = '')) %>% st_transform(crs = 4269)

briolines <- transitroutes %>% filter(str_detect(route_long_name, 'BRIO'))

rivers <- read_sf(paste(data_folder, "/MajorRivers_dd83.shp", sep = '')) %>%
  st_transform(crs = 4269) %>%
  filter(NAME == "Rio Grande") %>% 
  st_crop(y = geo_bb(elpaso, scale_factor = 1.1)) %>% 
  st_union() %>% 
  st_buffer(.003)


futureLU <- read_sf(paste(data_folder, "/FutureLandUse.shp", sep = '')) %>% st_transform(crs = 4269)

bounds <- geo_bb(briolines, scale_factor = 1.5)

elpas <- elpaso %>% st_crop(y = bounds)
riv <- rivers %>% st_crop(y = bounds)
flu <- futureLU %>% st_crop(y = bounds)


ftbliss <- futureLU %>% filter(COMMENTS %in% c("Fort Bliss Military"))
ftbliss_small <- flu %>% filter(COMMENTS %in% c("Fort Bliss Military"))

airport <- futureLU %>% filter(COMMENTS %in% c("Fort Bliss Mixed Use (Airport)"))


airport_small <- flu %>% filter(COMMENTS %in% c("Fort Bliss Mixed Use (Airport)"))


mtns <- futureLU %>% filter(COMMENTS %in% c("Preserve")) %>% arrange(-Shape_Area) %>% slice(1:2)

mtns_small <- flu %>% filter(COMMENTS %in% c("Preserve")) %>% arrange(-Shape_Area) %>% slice(1:2)

juarez <- read_sf(paste(data_folder, "/ciudad-juarez-city-blocks.shp", sep = '')) %>% st_transform(crs = 4269)
juar <- juarez  %>% st_crop(y = bounds)

mxroads <-  read_sf(paste(data_folder, "/carreteras.kml", sep = '')) %>% st_transform(crs = 4269)
#transitstops <-  read_sf(paste(data_folder, "/transit_stops.geojson", sep = ''))

#brio1 <- read_sf("https://services1.arcgis.com/hyTVSIhR7dHyDsJF/arcgis/rest/services/Brio_2021/FeatureServer")
```

```{r}
# brio bounds
ggplot(mxroads)+
  geom_sf()+
  geom_sf(data = elpaso)



```


```{r}
censusvars <- c("B01001_001E", # ACS total Pop estimate
              "B25002_001E", # Estimate of total housing units
              "B25002_003E", # Number of vacant housing units
              "B19013_001E", # Median HH Income ($)
              "B02001_002E", # People describing themselves as "white alone"
              "B06009_006E",
              "B01001I_001E", # Hispanic or Latino 
              "B08014_001E",
              "B09001_002E", # Population under 18
              "B10052_002E", # Disability
              "B25075_001E", # House value
              "B08014_002E") # No vehicle available


elpaso <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = censusvars, 
                             geometry = T,
                             state = "TX", 
                             county = "El Paso", 
                             output = "wide") 


elpaso <- elpaso %>%
  rename(
    total_pop.2020 = B01001_001E,
    total_HU.2020 = B25002_001E,
    total_vacant.2020 = B25002_003E,
    med_HH_Income.2020 = B19013_001E,
    total_White.2020 = B02001_002E,
    total_GradDeg.2020 = B06009_006E,
    total_HL.2020 = B01001I_001E,
    noV.2020 = B08014_002E,
    under18.2020 = B09001_002E,
    disAb.2020 = B10052_002E,
    Value = B25075_001E
  ) %>%
    mutate(vacancyPct.2020 = total_vacant.2020/total_HU.2020,
         pctWhite.2020 = total_White.2020/total_pop.2020,
         pctHL.2020 = total_HL.2020/total_pop.2020,
         pctNV.2020 = noV.2020/total_HU.2020*100,
         pctUnder18.2020 = under18.2020/total_pop.2020,
         pctDisAb.2020 = disAb.2020/total_pop.2020,
         area_sqmile = st_area(geometry)/2590000,
         pop_dense = as.numeric(total_pop.2020 / area_sqmile)
         ) %>%
  st_as_sf(crs = 4269) # Turn shp into sf object and project as WGS84

```


```{r}
#map of el paso geog and pop dense

ggplot()+
  geom_sf(data = elpaso, aes(fill = pop_dense), color = NA)+
  geom_sf(data = ftbliss, fill = 'darkgreen', color = NA)+
  geom_sf(data = mtns, fill = 'darkgrey', color = NA)+
  geom_sf(data = airport, fill = 'darkgreen', color = NA)+
  #geom_sf(data = juarez, fill = NA, color = 'lightgrey', alpha = .5)+
  geom_sf(data = rivers, fill = 'lightblue', color = NA)+
  paletteer::scale_fill_paletteer_c("grDevices::Red-Yellow", -1, labels= comma)+
  labs(fill = 'Population per \nSquare Mile', title = '')+
  theme(legend.position = 'left')+
  mapTheme()


```

```{r}
ggplot(transitroutes)+
  geom_sf()


ggplot()+
  #geom_sf(data = water, fill = 'lightblue', color = NA)+
  geom_sf(data = elpaso, aes(fill = pop_dense), color = NA, alpha =.5)+
  geom_sf(data = ftbliss, fill = 'darkgreen', color = NA, alpha =.5)+
  geom_sf(data = mtns, fill = 'green', color = NA, alpha =.5)+
  geom_sf(data = airport, fill = 'darkgreen', color = NA, alpha =.5)+
  geom_sf(data = briolines, size = 2, color = 'white')+
 paletteer::scale_fill_paletteer_c("grDevices::Red-Yellow", -1)+
  labs(fill = 'Population per \nSquare Mile', title = 'BRIO Bus Rapid Transit Lines')+
  mapTheme()+
  theme(legend.position = 'none') 



```
```{r}


ggplot()+

  #geom_sf(data = water, fill = 'lightblue', color = NA)+
  geom_sf(data = elpas, aes(fill = pop_dense), color = NA)+
  geom_sf(data = ftbliss_small, fill = 'darkgreen', color = NA)+
  geom_sf(data = mtns_small, fill = 'green', color = NA)+
  geom_sf(data = airport_small, fill = 'darkgreen', color = NA)+
  geom_sf(data = briolines, size = 2, aes(color = route_long_name), alpha= 1)+
   # geom_sf(data = juar, fill = NA, color = 'lightgrey', alpha = .5)+

    geom_sf(data = rivers %>% st_crop(y = bounds), fill = 'lightblue', color = NA)+

  scale_fill_paletteer_c("grDevices::Red-Yellow", -1)+
  scale_color_manual(values = c('#B0C72C','#660066','#00A8E7'))+
  ##B0C72C Alameda
  #660066 dyer
  #00A8E7 mesa
  #FFFFFF montana
  labs(fill = 'Population per \nSquare Mile', title = '')+
  mapTheme()+
  theme(legend.position = 'none')

```
invert pop dense symbology
add 4th brio line
  - color lines

local bus routes map

```{r}

notbrio <- transitroutes %>% filter(!str_detect(route_long_name, 'BRIO'))


ggplot()+

  #geom_sf(data = water, fill = 'lightblue', color = NA)+
  geom_sf(data = elpas, fill=NA, color = 'lightgrey', alpha = .3)+
  geom_sf(data = ftbliss_small, fill = 'darkgreen', color = NA)+
  geom_sf(data = mtns_small, fill = 'green', color = NA)+
  geom_sf(data = airport_small, fill = 'darkgreen', color = NA)+
  geom_sf(data = briolines, size = 2, aes(color = route_long_name), alpha= 1)+
  geom_sf(data = notbrio)+
    geom_sf(data = rivers %>% st_crop(y = bounds), fill = 'lightblue', color = NA)+

  scale_fill_paletteer_c("grDevices::Red-Yellow", -1)+
  scale_color_manual(values = c('#B0C72C','#660066','#00A8E7'))+
  ##B0C72C Alameda
  #660066 dyer
  #00A8E7 mesa
  #FFFFFF montana
  labs(title = 'Local Bus Routes')+
  mapTheme()+
  theme(legend.position = 'none')

```

```{r}

g <- ggplot()+
  geom_sf(data = briolines %>% select(-route_long_name), size = 1.5, aes(color = route_id))+

  geom_sf(data = notbrio %>% select(-route_long_name), alpha = .75, color = 'grey')+
  geom_sf(data = notbrio, aes(group = route_long_name), color = 'red')+
  mapTheme+
  scale_color_manual(values = c('#B0C72C','#660066','#00A8E7'))+
  labs(title = 'Sun Metro Local Bus Network',
       subtitle = '{closest_state}')+
  theme(legend.position = 'none')+
  transition_states(route_long_name)+
  exit_fade()

animate(g, duration = 15, fps = 10, bg = 'black')

anim_save('citybusses.gif', g, path = "C:/Users/cchue/Documents/Penn MUSA/Spring/Practicum",  duration = 15, fps = 10, bg = 'black')
    
```
```{r}

elpaso <- get_acs(geography = "tract",
                             year = 2020, 
                             variables = "B01001_001E", 
                             geometry = T,
                             state = "TX", 
                             county = "El Paso", 
                             output = "wide") 

elpaso_outline <- elpaso %>% st_union() %>% sf::st_cast()

hex <- st_make_grid(elpaso_outline, cellsize = .01, crs = 4269,  square = F)  %>%  st_sf() 

hex <- hex[elpaso,] %>%
  mutate(uniqueID = rownames(.))

ggplot(hex)+
  geom_sf()
```

```{r}

riderstops_sf <- read_csv(paste(data_folder, "/riderstops1.csv", sep = '')) %>%
  filter(!is.na(stop_lat)) %>%
  st_as_sf(coords = c('stop_lon', 'stop_lat'), crs = 4269) 

stop_riders_agg <- riderstops_sf %>% group_by(TP) %>% summarise(ridership = sum(Ons) + sum(Offs))

ggplot(stop_riders_agg)+
  geom_sf()+
  geom_sf(data = hex, fill = NA)

ridership_net <- stop_riders_agg %>% 
  dplyr::select(ridership) %>% 
  aggregate(., hex, sum) %>%
  mutate(ridership = replace_na(ridership, 0))

```

```{r}

ggplot(ridership_net %>% st_crop(y= bounds) %>% filter(ridership > 0))+
  geom_sf(aes(fill = ridership), color = NA)+
  geom_sf(data = ridership_net %>% st_crop(y= bounds) %>%  filter(ridership == 0), color = NA, fill = '#fbfae4')+
  scale_fill_paletteer_c("grDevices::Red-Yellow", -1)+
  theme(legend.position = 'none')+
  mapTheme()




```



