---
title: "graphs outlines for web app"
author: "Charlie Huemmler"
date: "2023-04-21"
output: 
  rmdformats::material:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(tidyverse)
library(scales)
library(cowplot)
library(here)
library(jsonlite)
```

## Ridership graphs 

```{r}


data_folder <- file.path(
  here() %>% 
    dirname(), 'data')

final_hex <- read_sf("final_hex7.geojson")

#final_hex <- final_data


riderstops <- read.csv(paste(data_folder, "/riderstops1.csv", sep = '')) %>%
  na.omit(riderstops[, c("stop_lat", "stop_lon")]) %>% 
  st_as_sf(coords = c("stop_lon", "stop_lat"), crs = 4269) %>%
  dplyr::select(RT) %>%
  mutate(
    type = case_when(
      RT == 2 ~ "Local",
      RT == 7 ~ "Local",
      RT == 10 ~ "Local",
      RT == 14 ~ "Local",
      RT == 15 ~ "Local",
      RT == 24 ~ "Local",
      RT == 25 ~ "Local",
      RT == 32 ~ "Local",
      RT == 33 ~ "Local",
      RT == 34 ~ "Local",
      RT == 35 ~ "Local",
      RT == 36 ~ "Local",
      RT == 37 ~ "Local",
      RT == 50 ~ "Local",
      RT == 51 ~ "Local",
      RT == 52 ~ "Local",
      RT == 53 ~ "Local",
      RT == 54 ~ "Local",
      RT == 58 ~ "Local",
      RT == 61 ~ "Local",
      RT == 62 ~ "Local",
      RT == 63 ~ "Local",
      RT == 64 ~ "Local",
      RT == 65 ~ "Local",
      RT == 66 ~ "Local",
      RT == 67 ~ "Local",
      RT == 68 ~ "Local",
      RT == 69 ~ "Local",
      RT == 72 ~ "Local",
      RT == 74 ~ "Local",
      RT == 86 ~ "Local",
      RT == 4 ~ "Circulator",
      RT == 8 ~ "Circulator",
      RT == 5 ~ "Express",
      RT == 6 ~ "Express",
      RT == 26 ~ "Express",
      RT == 59 ~ "Express",
      RT == 76 ~ "Express",
      RT == 11 ~ "Feeder",
      RT == 12 ~ "Feeder",
      RT == 13 ~ "Feeder",
      RT == 16 ~ "Feeder",
      RT == 19 ~ "Feeder",
      RT == 43 ~ "Feeder",
      RT == 44 ~ "Feeder",
      RT == 46 ~ "Feeder",
      RT == 56 ~ "Feeder",
      RT == 60 ~ "Feeder",
      RT == 84 ~ "Feeder",
      RT == 89 ~ "Feeder",
      RT == 205 ~ "BRIO",
      RT == 206 ~ "BRIO",
      RT == 207 ~ "BRIO",
      RT == 208 ~ "BRIO",
      RT == 17 ~ "Other",
      RT == 20 ~ "Other",
      RT == 21 ~ "Other",
      RT == 41 ~ "Other",
      RT == 82 ~ "Other",
      RT == 87 ~ "Other",
      RT == 500 ~ "Streetcar"
    )
  ) %>% filter(type == 'Local')






```

## merge with current routes

```{r}

merge <- st_join(riderstops, final_hex, join = st_intersects) %>% st_drop_geometry()


## python group by aggregate 
# joined = joined.groupby('RT').agg({'ridership_per_stop_left': 'sum', 'pred_ridership_per_stop_left': 'sum', 'whitePop_left': 'mean', 'blackPop_left': 'mean', 'asianPop_left': 'mean', 'hlPop_left': 'mean', 'otherRacePop_left': 'mean', 'nhPop_left': 'mean', 'aiPop_left': 'mean', 'disability_left': 'sum', 'medHHInc_left': 'mean', 'employmentHHMix_left': 'mean'})

route_hex <- merge %>% group_by(RT) %>%
  summarize(actual_ridership = sum(ridership_per_stop, na.rm = T),
            predicted_ridership = sum(pred_ridership_per_stop, na.rm = T),
            whitePop = mean(whitePopPct, na.rm = T),
            blackPop = mean(blackPopPct, na.rm = T),
            asianPop = mean(asianPopPct, na.rm = T),
            hlPop = mean(hlPopPct, na.rm = T),
            otherRacePop = mean(otherRacePopPct, na.rm = T),
            nhPop = mean(nhPopPct, na.rm = T),
            aiPop = mean(aiPopPct, na.rm = T),
            disability = sum(disability, na.rm = T),
            medHHInc = mean(medHHInc, na.rm = T),
            employmentHHMix = mean(employmentHHMix, na.rm = T))%>% 
  mutate(sum_race_pct = whitePop + blackPop + asianPop + hlPop + otherRacePop + nhPop + aiPop)


route_hex <- route_hex %>% mutate( highlight = ifelse(RT == sample(1:nrow(.),1), "y","n"))



```




```{r }

route_hex %>% gather(-highlight, -RT, key = RT, val = val) %>% ggplot()+
  geom_jitter(data = . %>% filter(highlight == 'n'), 
              aes(y = val, x = ""),
              color = 'grey',
              alpha = .5)+
    geom_jitter(data = . %>% filter(highlight == 'y'), 
              aes(y = val, x = ""),
              color = 'orange',
              width = .05)+
  scale_y_continuous(label = comma)+
  theme_minimal()+
  theme(strip.text = element_text(size = 9))+
  labs(y='',x='', title = "")+
  facet_wrap(~RT, scales = 'free')



```

## looking at all geometry types

```{r}
grid.arrange(ncol=2,
             ggplot()+
               geom_sf(data=acs_ep, aes(fill=whitePopPct), color=NA)+
               scale_fill_paletteer_c("grDevices::Red-Yellow", -1, name="%")+
               labs(title="% White bt Tract",
                    caption="Data: ACS, 2020")+
               mapTheme,
             ggplot()+
               geom_sf(data=acs_race_hex, aes(fill=whitePopPct), color=NA)+
               scale_fill_paletteer_c("grDevices::Red-Yellow", -1, name="%")+
               labs(title="% White by Hex",
                    caption="Data: ACS, 2020")+
               mapTheme,
             ggplot()+
               geom_sf(data=acs_ep, aes(fill=blackPopPct), color=NA)+
               scale_fill_paletteer_c("grDevices::Red-Yellow", -1, name="%")+
               labs(title="% Black by Tract",
                    caption="Data: ACS, 2020")+
               mapTheme,
             ggplot()+
               geom_sf(data=acs_race_hex, aes(fill=blackPopPct), color=NA)+
               scale_fill_paletteer_c("grDevices::Red-Yellow", -1, name="%")+
               labs(title="% Black by Hex",
                    caption="Data: ACS, 2020")+
               mapTheme
)


```
```{r}
write_json(route_hex,  path =  'current_routes_db_agg')

```

